publisher_scaled_joint_trajectory_controller:
  ros__parameters:

    controller_name: "ur_script"

    goal_names: ['pose0', 'pose1', 'pose2', 'pose3', 'pose4', 'pose5', 'pose6', 'pose7']
    pose0:
      positions: [-2.619051548 ,-2.1876225471,-1.4784646352, 0.5738267303,-1.5694968382, 1.2770213962]
      move_type: "movej"
      velocity: 0.0
      acceleration: 0.0
      movement_duration: [10, 0]
      laser_on: false

    pose1:
      positions: [-2.5705173455,-1.5519871354,-1.8795883141, 1.0906766176,-2.2532237212, 0.1310870469]
      move_type: "movej"
      velocity: 0.0
      acceleration: 0.0
      movement_duration: [10, 0]
      laser_on: false

    pose2:
      positions: [-2.619051548 ,-2.1876225471,-1.4784646352, 0.5738267303,-1.5694968382, 1.2770213962]
      move_type: "movej"
      velocity: 0.0
      acceleration: 0.0
      movement_duration: [10, 0]
      laser_on: false

    pose3:
      positions: [-1.103228159 ,-2.075589323 ,-1.5709704838, 2.8130660534,-2.7204599778, 1.6450837731]
      move_type: "movej"
      velocity: 0.0
      acceleration: 0.0
      movement_duration: [10, 0]
      laser_on: false

    pose4:
      positions: [-2.619051548 ,-2.1876225471,-1.4784646352, 0.5738267303,-1.5694968382, 1.2770213962]
      move_type: "movej"
      velocity: 0.0
      acceleration: 0.0
      movement_duration: [10, 0]
      laser_on: false    

    pose5:
      positions: [-2.5705173455,-1.5519871354,-1.8795883141, 1.0906766176,-2.2532237212, 0.1310870469]
      move_type: "movej"
      velocity: 0.0
      acceleration: 0.0
      movement_duration: [10, 0]
      laser_on: false

    pose6:
      positions: [-2.619051548 ,-2.1876225471,-1.4784646352, 0.5738267303,-1.5694968382, 1.2770213962]
      move_type: "movej"
      velocity: 0.0
      acceleration: 0.0
      movement_duration: [10, 0]
      laser_on: false    

    pose7:
      positions: [-1.5707854998e+00,-1.5707794905e+00,-1.5707604188e+00, 1.5707907200e+00,-3.1416063229e+00, 3.8691934126e-05]
      move_type: "movej"
      velocity: 0.0
      acceleration: 0.0
      movement_duration: [10, 0]
      laser_on: false



    joints:
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - shoulder_pan_joint

    check_starting_point: true
    starting_point_limits:
      shoulder_lift_joint: [-1.7, -1.4]
      elbow_joint: [-1.7, -1.4]
      wrist_1_joint: [-1.7, -1.4]
      wrist_2_joint: [1.4, 1.7]
      wrist_3_joint: [-3.2, 3.]
      shoulder_pan_joint: [-0.2, 0.2]
